name: 'Install Allegro 5 dependencies on Windows/Linux'
description: 'Quick installation to enable build of Allegro 5'
inputs:
  compiler:
    description: 'What compiler? (gcc, mingw, msvc)'
    required: true

runs:
  using: composite
  steps:
    - name: Setup Windows MSVC packages for Allegro 5
      if: inputs.compiler == 'msvc'
      shell: bash
      run: |
        vcpkg install --triplet x64-windows-static \
          bzip2 \
          freetype[core] \
          libflac \
          libjpeg-turbo \
          libogg \
          libpng \
          libtheora \
          libvorbis \
          libwebp[core] \
          minimp3 \
          openal-soft \
          opus \
          opusfile \
          physfs \
          zlib \
          directxsdk

    - name: Setup Windows MinGW packages for Allegro 5
      if: inputs.compiler == 'mingw'      
      uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        release: false
        location: 'C:\msys64'
        update: true
        install: >-
          mingw-w64-ucrt-x86_64-gcc
          mingw-w64-ucrt-x86_64-cmake
          mingw-w64-ucrt-x86_64-ninja
          make
          mingw-w64-ucrt-x86_64-physfs
          mingw-w64-ucrt-x86_64-freetype
          mingw-w64-ucrt-x86_64-libvorbis
          mingw-w64-ucrt-x86_64-flac
          mingw-w64-ucrt-x86_64-dumb
          mingw-w64-ucrt-x86_64-libtheora
          mingw-w64-ucrt-x86_64-libjpeg-turbo
          mingw-w64-ucrt-x86_64-opusfile
          mingw-w64-ucrt-x86_64-enet
          mingw-w64-ucrt-x86_64-libwebp
          mingw-w64-ucrt-x86_64-libopenmpt
        
    - name: Setup Ubuntu packages for Allegro 5
      if: inputs.compiler == 'gcc'
      shell: bash
      run: |
        sudo apt-get update && \
        sudo apt-get install -qq -y -o=Dpkg::Use-Pty=0 \
          xvfb \
          libvorbis-dev \
          libtheora-dev \
          libwebp-dev \
          libphysfs-dev \
          libopusfile-dev \
          libdumb1-dev \
          libflac-dev \
          libpulse-dev \
          libgtk-3-dev \
          pandoc \
          libcurl4-openssl-dev \
          libenet-dev \
          pulseaudio \
          libasound2-dev \
          libopenal-dev \
          libgl1-mesa-dev \
          libglu-dev \
          libopenmpt-dev