name: CMake action build example test

on:
#  push:
#    branches:
#      - master
  workflow_dispatch:
    inputs:
      make_prerelease:
        description: Make it a pre-release
        type: string
        required: false
        default: 'false'
      bump_type:
        description: What to bump [M,m,r,rc,snapshot,*]
        type: string
        required: false
        default: 'm'
      use_experimental_branch:
        description: Use the experimental branch
        type: boolean
        required: false
        default: false


jobs:
  build:
    #continue-on-error: true
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - if: ${{ inputs.use_experimental_branch == 'false' }}
        name: Build
        uses: LunarisLib/actions/CMake@master
        with:
          checkout: 'true'
          project_path: ./.examples/CMake_project/
          artifact_name: ${{ matrix.os }}_PROJECT
          
      - if: ${{ inputs.use_experimental_branch == 'true' }}
        name: Build
        uses: LunarisLib/actions/CMake@experimental
        with:
          checkout: 'true'
          project_path: ./.examples/CMake_project/
          artifact_name: ${{ matrix.os }}_PROJECT
          
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - if: ${{ inputs.use_experimental_branch == 'false' }}
        name: Versioning
        id: versioning
        uses: LunarisLib/actions/Versioning@master
        with:
          kind: ${{ inputs.bump_type }}
          project: CMAKE_PROJECT

      - if: ${{ inputs.use_experimental_branch == 'true' }}
        name: Versioning
        id: versioning-ex
        uses: LunarisLib/actions/Versioning@experimental
        with:
          kind: ${{ inputs.bump_type }}
          project: CMAKE_PROJECT

          
      - if: ${{ inputs.use_experimental_branch == 'false' }}
        name: Publish
        uses: LunarisLib/actions/Publisher@master
        with:
          title: "CMake Release"
          body: "This is a sample of a body to the example of a CMake project"
          tag_name: ${{ steps.versioning.outputs.version }}_CMAKE
          prerelease: ${{ inputs.make_prerelease }}

      - if: ${{ inputs.use_experimental_branch == 'true' }}
        name: Publish
        uses: LunarisLib/actions/Publisher@experimental
        with:
          title: "CMake Release experimental"
          body: "This is a sample of a body to the example of a CMake project"
          tag_name: ${{ steps.versioning-ex.outputs.version }}_CMAKE
          prerelease: ${{ inputs.make_prerelease }}


    